name: tokei
base: core18
version: git
summary:  A program that allows you to count your code, quickly
description: |
  Tokei is a program that displays statistics about your code. Tokei will
  show number of files, total lines within those files and code, comments,
  and blanks grouped by language.

grade: stable
confinement: strict

parts:
  tokei:
    plugin: rust
    source: .

apps:
  tokei:
    command: tokei
    plugs:
      - home
